[Interface]
Listen = 0.0.0.0:MQVPN2_PORT
Subnet = MQVPN2_SUBNET
TunName = mqvpn2
LogLevel = info

[TLS]
Cert = /etc/mqvpn2/server.crt
Key = /etc/mqvpn2/server.key

[Auth]
Key = MQVPN2_PASS
MaxClients = 1

[Multipath]
Scheduler = wlb
CC = cubic
InitMaxPathId = 128

[Reorder]
Enabled = off

[Hybrid]
Enabled = false

[Routes]
Route = 10.0.0.0/8
Route = 172.16.0.0/12
Route = 192.168.0.0/16
