[Interface]
Listen = 0.0.0.0:MQVPN_PORT
Subnet = 10.255.249.0/24
TunName = mqvpn0
LogLevel = info

[TLS]
Cert = /etc/mqvpn/server.crt
Key = /etc/mqvpn/server.key

[Auth]
Key = MQVPN_PASS
MaxClients = 64

[Multipath]
Scheduler = wlb

[Routes]
Route = 192.168.100.0/24
